/******************************************
Treehouse FSJS Techdegree:
project 1 - A Random Quote Generator
******************************************/

// For assistance:
// Check the "Project Resources" section of the project instructions
// Reach out in your Slack community - https://treehouse-fsjs-102.slack.com/app_redirect?channel=chit-chat

/***
 * `quotes` array
 ***/

//Quotes array containing objects with quotes, source, and relative information
const quotes = [
  {
    quote: 'When something is important enough, you do it even if the odds are not in your favor.',
    source: 'Elon Musk',
    tags: ['Motivational'],
  },
  {
    quote: 'As we look ahead into the next century, leaders will be those who empower others.',
    source: 'Bill Gates',
    tags: ['Motivational', 'Business'],
  },
  {
    quote: 'Learn to sit back and observe. Not everything needs a reaction',
    source: 'Thomas Shelby',
    citation: 'Peaky Blinders',
    year: 2015,
    tags: ['Politics', 'Business'],
  },
  {
    quote: 'We must be the change we wish to see in the world.',
    source: 'Mahatma Gandhi',
    year: 1989,
    tags: ['Politics'],
  },
  {
    quote: 'The art challenges the technology and the technology inspires the art.',
    source: 'John Lasseter',
    tags: ['Technology'],
  },
];

/***
 * `getRandomQuote` function
 ***/

/*
    The functions accepts the quotes array generates a random value between 0 and quotes array length
    and return the a random quote object from the array
*/
const getRandomQuote = function (quotes) {
  const randomQuoteNumber = Math.floor(Math.random() * quotes.length);
  return quotes[randomQuoteNumber];
};

/*
    The function generates a random RGB background color and
    assigns it to the body and tags elements
*/
const randomBgColor = function () {
  const r = Math.floor(Math.random() * 256);
  const g = Math.floor(Math.random() * 256);
  const b = Math.floor(Math.random() * 256);

  const bgColor = `rgb(${r}, ${g}, ${b})`;

  document.querySelector('body').style.backgroundColor = bgColor;
  const tags = document.getElementsByClassName('tags');

  for (let i = 0; i < tags.length; i++) {
    tags[i].style.backgroundColor = bgColor;
  }
};

// console.log(getRandomQuote(quotes));

/***
 * `printQuote` function
 ***/

/*
    The function prints a random quote generated by getRandomQuote funtion
    on the page.
*/

const printQuote = function () {
  const randQuote = getRandomQuote(quotes);
  let htmlOutput = `
  <p class="quote"> ${randQuote.quote} </p>
  <p class="source"> ${randQuote.source}
  `;

  //Check if the random quote has a citation property
  if (randQuote.citation !== undefined) {
    htmlOutput += `<span class="citation"> ${randQuote.citation} </span>`;
  }
  //Check if the random quote has a year property
  if (randQuote.year !== undefined) {
    htmlOutput += `<span class="year"> ${randQuote.year} </span>`;
  }

  //Adding tags (extra)
  htmlOutput += `| Tags: `;

  for (let i = 0; i < randQuote.tags.length; i++) {
    htmlOutput += `<span class="tags"> ${randQuote.tags[i]} </span>`;
  }

  htmlOutput += `</p>`;

  //Outputs the final html to the page
  document.getElementById('quote-box').innerHTML = htmlOutput;
  //Changes background and elements color
  randomBgColor();

  return htmlOutput;
};
printQuote();

//  The function generates a new quote on the page every 10 seconds
const autoQuoteRefresh = function () {
  setInterval(function () {
    printQuote();
  }, 10000);
};
autoQuoteRefresh();

/***
 * click event listener for the print quote button
 * DO NOT CHANGE THE CODE BELOW!!
 ***/

//Show another quote button functionality
document.getElementById('load-quote').addEventListener('click', printQuote, false);
